#!/bin/sh
rsync -avz --exclude='.git' --exclude='*~' . danking@login.seas.harvard.edu:harvard-pl-website
ssh danking@login.seas.harvard.edu 'rsync -avz harvard-pl-website danking@pub-aws.seas.harvard.edu:/seas/web/sites_static/pl.seas.harvard.edu/htdocs'
